# yaml-language-server: $schema=https://gcpw.art/tvs/schemas/5.9.0.json

# Documented configuration file.
# Data that is required will be denoted as such. Anything that isn't required can be commented out / removed.
# More options are available than are in this file, and links are provided to relevant parts of the documentation.

##### VISUAL EFFECTS #####
# REFERENCE:
# https://greenhillplaza.notion.site/Visual-Effects-68ae52d438344b9598cd4ac86cc2a0e5
#
# These options control the picture and the window.
##########################

applicationTitle: Television Simulator Public Beta # Optional. The title of the webpage; make it your own!
scanlines: true # Optional. Scanlines are enabled by default but if you don't want them you can set this to false. On a real CRT it's best to disable these and shadow masks.
shadowMask: aperture-grille # Optional. The default shadow mask to simulate a CRT screen. Values are slot-mask, dot-mask, or aperture-grille. To disable, set to false.
noise: 0.15 # Optional. Default amount of picture noise to apply
blur: 1 # Optional. Default amount of blur to apply to the picture; set to false to disable
bezel: flat # Optional. You can specify a bezel image to go around the outside of the screen. Values are none, cylindrical or flat.
animateChannelChange: false
changeChannelNoise: false
border: placeholders/border.png # Optional. You can specify a repeating pattern a background image around the outside of the screen
# warmup: false # Optional. By default the TV will warm up and cool down when you power it on and off. If you want to disable this set to false. If set to a number, it will be the duration of the warmup in seconds.

# Uncomment the lines below to use the digital cable box theme instead of the default on-screen displays
# osd:
#   theme: digital
#   primaryColor: "#00FFFC"
#   accentColor: "#F600FF"

osd:
   theme: sat2007
   primaryColor: orange


noSignalContent: # Optional. You can specify content to show when a channel is off the air.
  image: placeholders/no-signal.png

defaultChannel: 1 # Required. The default channel to start on when visiting the page.

channels: # starts a list of channels. Every channel below begins with a "-" as that lets YAML know we're defining a list.

- number: 1
  name: plankussy
  abbr: PLSY
  icon: https://file.garden/aUYIWVAKvQxCBY-_/database/images/fishmcbitesapp.jpeg
  pip:
  a:
    image: p/ogplankussy.png
  b:
    image: p/fih.png
  backgroundAudio: https://dn710204.ca.archive.org/0/items/SUPERCELL_Clash-of-Clans-Soundtrack-2023/Clash%20of%20Clans/AudioOnly/Halloween-Music/Compilation/OGG/Home_music_BuilderBase_Part_1-2_Halloween.mp3

- number: 2
  name: what the sigma
  abbr: SEP
  description: INCREDIBOX KATS DETECTED!!!! OwO thats grilled chicken
  youtube-playlist:
    src: PLpKW54fMiMFxdGQSefzMAO3r3xt3IOIry
    shuffle: true

- number: 3
  name: TVS Update News
  abbr: NEWS
  feed-reader:
    src: https://docs.tvs.gcpw.art/tvs-changelog.xml
    title: TVS Update News
    refreshInterval: 300
    scrollSpeed: 35
    scrollDelay: 6

- number: 4
  name: Guide 1989 custom colors example
  noiseBlendMode: multiply
  guide:
    theme: "1989"
    logo: p/plankussy.png
    primaryColor: white # Optional. The primary color of the guide; this is used for the default background color of guide cells
    secondaryColor: blue # Optional. The secondary color of the guide; this is used for the text color of headers and channel numbers
    textColor: black # Optional. The text color of the guide; this is used for the text color of guide cells
    alerts:
      - position: 32
        text: |
          Plankussy... throbbing...


- number: 5
  name: oh fuck
  abbr: FUCK
  feed-reader:
    src: https://tvseagate.github.io/cbt.rss
    title: TVS Update News
    refreshInterval: 300
    scrollSpeed: 35
    scrollDelay: 6

- number: 6
  name: KCNS_20130309_060000_Noticias_MundoFox.mp4
  abbr: KCNS
  title: Noticias MundoFox
  description: Preview the hottest movies on Pay-Per-View and On Demand!
  video: https://file.garden/aUYIWVAKvQxCBY-_/database/videos/KCNS_20130309_060000_Noticias_MundoFox.mp4

- number: 6
  name: WMAR_20110605_230000_Jimmy_Kimmel_Live.mp4
  abbr: WMAR
  title: Jimmy Kimmel Live
  video: https://file.garden/aUYIWVAKvQxCBY-_/database/videos/WMAR_20110605_230000_Jimmy_Kimmel_Live.mp4