# yaml-language-server: $schema=https://gcpw.art/tvs/schemas/5.9.0.json

# Documented configuration file.
# Data that is required will be denoted as such. Anything that isn't required can be commented out / removed.
# More options are available than are in this file, and links are provided to relevant parts of the documentation.

##### VISUAL EFFECTS #####
# REFERENCE:
# https://greenhillplaza.notion.site/Visual-Effects-68ae52d438344b9598cd4ac86cc2a0e5
#
# These options control the picture and the window.
##########################
applicationTitle: Dunceville Hotel TV # What the DirecTV UI might have looked like in 2012

startUnmuted: true

osd:
  theme: digital


dimensions:
  screenWidth: 800
  screenHeight: 600

noSignalContent: # Optional. You can specify content to show when a channel is off the air.
  image: placeholders/no-signal.png

defaultChannel: 1 # Required. The default channel to start on when visiting the page.

channels: # starts a list of channels. Every channel below begins with a "-" as that lets YAML know we're defining a list.

- number: 1
  name: plankussy
  abbr: PLSY
  icon: https://file.garden/aUYIWVAKvQxCBY-_/database/images/fishmcbitesapp.jpeg

- number: 2
  name: TV36
  abbr: TV36
  iframe:
    src: https://tv36.pages.dev
    allowInteraction: true

- number: 3
  name: TV25
  abbr: TV25
  iframe:
    src: https://tv25.pages.dev
    allowInteraction: true
