# yaml-language-server: $schema=https://gcpw.art/tvs/schemas/5.9.0.json

# Documented configuration file.
# Data that is required will be denoted as such. Anything that isn't required can be commented out / removed.
# More options are available than are in this file, and links are provided to relevant parts of the documentation.

##### VISUAL EFFECTS #####
# REFERENCE:
# https://greenhillplaza.notion.site/Visual-Effects-68ae52d438344b9598cd4ac86cc2a0e5
#
# These options control the picture and the window.
##########################

applicationTitle: Television Seagate

scanlines: true 
shadowMask: aperture-grille 
noise: 0.15
blur: 1
bezel: flat 
animateChannelChange: false
changeChannelNoise: false
border: placeholders/border.png

#osd:
#   theme: sat2007
#   primaryColor: "#00FFFC"

osd:
  theme: sat1992 # 1990's analog C-band satellite receiver theme
  themeOptions:
    # showChannelInterference: false # by default, we display overlays of
    satellite: TV1 # the default satellite for all channels to be on. If unset, only channels with a satellite option set will display one.
    satellites: # you can define a list of different satellites; they'll be a letter and number combination followed by a 4-digit number representing the location in the sky
      TV2: 3600 # these are all arbitrary numbers
      TV3: 4100

startUnmuted: true

dimensions:
  screenWidth: 800
  screenHeight: 600

noSignalContent: # Optional. You can specify content to show when a channel is off the air.
  image: placeholders/no-signal.png

defaultChannel: 1 # Required. The default channel to start on when visiting the page.

channels: # starts a list of channels. Every channel below begins with a "-" as that lets YAML know we're defining a list.

- number: 1
  name: plankussy
  abbr: PLSY
  icon: https://file.garden/aUYIWVAKvQxCBY-_/database/images/fishmcbitesapp.jpeg
  pip:
   a:
    image: p/ogplankussy.png
   b:
    image: p/fih.png
  backgroundAudio: https://dn710204.ca.archive.org/0/items/SUPERCELL_Clash-of-Clans-Soundtrack-2023/Clash%20of%20Clans/AudioOnly/Halloween-Music/Compilation/OGG/Home_music_BuilderBase_Part_1-2_Halloween.mp3

- number: 2
  name: what the sigma
  abbr: SEP
  description: INCREDIBOX KATS DETECTED!!!! OwO thats grilled chicken
  youtube-playlist:
    src: PLpKW54fMiMFxdGQSefzMAO3r3xt3IOIry
    shuffle: true

- number: 3
  name: TVS Update News
  abbr: NEWS
  feed-reader:
    src: https://docs.tvs.gcpw.art/tvs-changelog.xml
    title: TVS Update News
    refreshInterval: 300
    scrollSpeed: 35
    scrollDelay: 6

- number: 4
  name: Guide 1989 custom colors example
  noiseBlendMode: multiply
  guide:
    theme: "1989"
    logo: p/plankussy.png
    primaryColor: white # Optional. The primary color of the guide; this is used for the default background color of guide cells
    secondaryColor: blue # Optional. The secondary color of the guide; this is used for the text color of headers and channel numbers
    textColor: black # Optional. The text color of the guide; this is used for the text color of guide cells
    alerts:
      - position: 32
        text: |
          Plankussy... throbbing...


- number: 5
  name: oh fuck
  abbr: FUCK
  feed-reader:
    src: https://tvseagate.github.io/cbt.rss
    title: shart
    refreshInterval: 300
    scrollSpeed: 35
    scrollDelay: 6

- number: 6
  name: KCNS_20130309_060000_Noticias_MundoFox.mp4
  abbr: KCNS
  title: Noticias MundoFox
  description: Preview the hottest movies on Pay-Per-View and On Demand!
  video: https://file.garden/aUYIWVAKvQxCBY-_/database/videos/KCNS_20130309_060000_Noticias_MundoFox.mp4

- number: 7
  name: WMAR_20110605_230000_Jimmy_Kimmel_Live.mp4
  abbr: WMAR
  title: Jimmy Kimmel Live
  video: https://file.garden/aUYIWVAKvQxCBY-_/database/videos/WMAR_20110605_230000_Jimmy_Kimmel_Live.mp4

- number: 8
  name: EAS
  abbr: EAS
  title: Current EAS Alerts
  feed-reader:
    src: https://api.weather.gov/alerts/active.atom?zone=OHZ070
    title: Current EAS Alerts
    refreshInterval: 300
    scrollSpeed: 35
    scrollDelay: 6

- number: 9
  name: Customer Information
  title: The new FiOS TV is here!
  abbr: CTF
  backgroundAudio: https://file.garden/aUYIWVAKvQxCBY-_/database/music/Quant5%20extended%20-%20UK%20Garage.mp3
  video: https://file.garden/aUYIWVAKvQxCBY-_/database/videos/new-fios.mp4

- number: 10
  name: Now Playing
  abbr: ITV
  backgroundAudio: http://radio.plaza.one/mp3
  backgroundAudioOptions:
    nowPlayingUrl: https://api.plaza.one/status
    nowPlayingProvider: plaza-one # Required if using nowPlayingUrl. Only a few providers are supported right now; see the documentation for more info.
  iframe:
   src: https://ourworldoftext.com/nowplaying
  
- number: 11
  name: Our World Of Text
  title: OWOT Spawn
  abbr: OWOT
  backgroundAudio: http://radio.plaza.one/mp3
  backgroundAudioOptions:
    nowPlayingUrl: https://api.plaza.one/status
    nowPlayingProvider: plaza-one 
  iframe:
   src: https://ourworldoftext.com/

- number: 12
  name: Bee Sting
  title: Bee Sting Programming
  description: elephant hit
  youtube-playlist:
    src: PLj6qdykhRWPlZ1aYt7ugMDfYXIANfV2gU
    shuffle: true
  themeOptions:
    satellite: TV2